### ISSUE TITLE
Missing static/images/favicon.ico file prevents from starting the server

### ISSUE THREAD

**Issue by happypoulp** [colinmeinke/universal-js#11]
Hi,

First, I really like your starter kit!

When trying to run the server I got this error that prevents from starting the server:

```
(local (master)~/Codes/universal-js)$ npm start --development

> universal-js@0.5.0 start /Users/me/Codes/universal-js
> node ./dist/server.js

Error: ENOENT: no such file or directory, stat '/Users/me/Codes/universal-js/static/images/favicon.ico'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at favicon (/Users/me/Codes/universal-js/node_modules/serve-favicon/index.js:64:15)
    at Object.<anonymous> (/Users/me/Codes/universal-js/dist/server.js:98:40)
    at Object.<anonymous> (/Users/me/Codes/universal-js/dist/server.js:132:31)
    at __webpack_require__ (/Users/me/Codes/universal-js/dist/server.js:21:30)
    at obj.__esModule.default (/Users/me/Codes/universal-js/dist/server.js:41:18)
    at Object.<anonymous> (/Users/me/Codes/universal-js/dist/server.js:44:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

Doing a `touch static/images/favicon.ico` fixed the issue but if you got a real favicon that would probably be better.

**Comment by colinmeinke** [comment]
:+1: Thanks for this! I forgot the static folder was in the .gitignore.
